// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDSExamNet7.Data;

#nullable disable

namespace SDSExamNet7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240529200801_UpdateRecyclableItemsAndTypes")]
    partial class UpdateRecyclableItemsAndTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDSExamNet7.Models.Entities.RecyclableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComputedRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RecyclableTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecyclableTypeId");

                    b.ToTable("RecyclableItem");
                });

            modelBuilder.Entity("SDSExamNet7.Models.Entities.RecyclableType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("RecyclableType");
                });

            modelBuilder.Entity("SDSExamNet7.Models.Entities.RecyclableItem", b =>
                {
                    b.HasOne("SDSExamNet7.Models.Entities.RecyclableType", "RecyclableType")
                        .WithMany("RecyclableItems")
                        .HasForeignKey("RecyclableTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecyclableType");
                });

            modelBuilder.Entity("SDSExamNet7.Models.Entities.RecyclableType", b =>
                {
                    b.Navigation("RecyclableItems");
                });
#pragma warning restore 612, 618
        }
    }
}
